### ISSUE TITLE
Is it possible to fix parameters in the Emax model?

### ISSUE THREAD

**Issue by iamstein** [yoshidk6/rstanemax#40]
What if I'd like to fix gamma = 1, or E0 = 0, or Emax = 100.  Is this possible?

**Comment by iamstein** [comment]
Sorry, dumb question.  I typed ?rstanemax and didn't see any help.  But ?stan_emax says how to do it.  Sorry.

**Comment by yoshidk6** [comment]
Thanks, the GitHub version now allows users to fix Emax in addition to gamma and E0
