### ISSUE TITLE
Can rstanemax estimate the proptional residual error?

### ISSUE THREAD

**Issue by Kokomole** [yoshidk6/rstanemax#44]
Dear author,

Thank you for developing this great package, which is very convenient to  build the Emax model. However, it seems only the addtive residual error can be estimated by the function `stan_emax`? I'm wondering whether the following proptional residual error can be estimated:

$$y = (e_0 + \frac{e_{max}\times x}{ec_{50}+x})\times (1+\varepsilon) $$

where 
$$\varepsilon \sim N(0, \sigma^2)$$

Many thanks to your help.

Best regards,
Min

**Comment by yoshidk6** [comment]
Thanks for using the package!
Unfortunately `rstanemax` doesn't have a functionality to use proportional error model.
I would suggest the followings as potential alternatives - each with own drawbacks but hopefully good enough approximation for most cases. 

- Perform Emax model on log-transformed data
- Use brms ([ref](https://rpubs.com/mvuorre/emax-brms)), specify observed value as weight in `bf()`/`brmsformula()` function ([ref](https://paul-buerkner.github.io/brms/reference/brmsformula.html))

**Comment by Kokomole** [comment]
Thank you author. Your answer is of great help to me and it have solved my problem.
